### ISSUE TITLE
Filenames with "+" get converted to spaces

### ISSUE THREAD

**Issue by athielen2** [deb-s3/deb-s3#11]
Our team recently ran into an issue where the filenames store within the package index were incorrect when updated with the latest version of deb-s3. There were ~10 packages we have stored in s3 that include a "+" in the version and path (e.g. `libnvinfer-plugin7=7.1.3-1+cuda10.2`). When we attempted to install the packages, the following error occurred for all packages:

`E: Failed to fetch s3://xxxx-xxx/xxx-xxx/private/pool/bionic/l/li/libnvinfer-plugin-dev_7.1.3-1 cuda10.2_arm64.deb  403  Forbidden`

Note that there is a space in the filename instead of a "+". A snippet of the package index generated by deb-s3 can be seen below:

**Incorrect Version**
```
Package: libnvinfer-plugin7
Version: 7.1.3-1+cuda10.2
Filename: pool/bionic/l/li/libnvinfer-plugin7_7.1.3-1 cuda10.2_arm64.deb
```

When we re-uploaded the packages with v0.10.0 of the original deb-s3 (https://github.com/krobertson/deb-s3/tree/0.10.0), the filename is correctly included in the package index: 

**Correct Version**
```Package: libnvinfer-plugin7
Version: 7.1.3-1+cuda10.2
Filename: pool/bionic/l/li/libnvinfer-plugin7_7.1.3-1+cuda10.2_arm64.deb
```

Looking through the source, this looks to be caused by replacing `URI.unescape` with `CGI.unescape` in `package.rb` (https://github.com/deb-s3/deb-s3/blob/master/lib/deb/s3/package.rb#L254)

**Comment by morph027** [comment]
Unable to reproduce, just created a small dummy package using [fpm](https://github.com/jordansissel/fpm/).

```
Filename: pool/jammy/z/zz/zzz_1.0+1337_all.deb
```

The template in https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/templates/package.erb#L43 is using https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/package.rb#L147-L149 and not the line w/ CGI.unescape.

Can you try to reproduce w/ latest version?

**Comment by laurentgoudet** [comment]
> Can you try to reproduce w/ latest version?

The latest version(s) of the `deb-s3` gem, which hadn't been updated in 4 years, broke source APT source repo which broke our production environment, i.e. I can confirm we are seeing the same issue.

> The template in https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/templates/package.erb#L43 is using https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/package.rb#L147-L149 and not the line w/ CGI.unescape.

Could it be because https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/package.rb#L147-L149 does:

```
  def url_filename_encoded(codename)
    @url_filename || "pool/#{codename}/#{self.name[0]}/#{self.name[0..1]}/#{s3_escape(File.basename(self.filename))}"
  end
```

and `@url_filename` is set when `extract_info` is called (in https://github.com/deb-s3/deb-s3/blob/0.11.5/lib/deb/s3/package.rb#L258)?

**Comment by morph027** [comment]
Recently i've been granted access to upload to rubygems, so latest version has been uploaded to https://rubygems.org/gems/deb-s3/versions/0.11.6

Works for me.

Upload:

```
# deb-s3 upload graphsurgeon-tf_8.5.1-1+cuda11.8_amd64.deb --bucket deb-s3-11 --codename test --access-key-id ... --secret-access-key ... --endpoint https://minio.morph027.de --sign ... --force-path-style
>> Retrieving existing manifests
>> Examining package file graphsurgeon-tf_8.5.1-1+cuda11.8_amd64.deb
>> Uploading packages and new manifests to S3
   -- Transferring pool/test/g/gr/graphsurgeon-tf_8.5.1-1+cuda11.8_amd64.deb
   -- Transferring dists/test/main/binary-amd64/Packages
   -- Transferring dists/test/main/binary-amd64/Packages.gz
   -- Transferring dists/test/main/binary-i386/Packages
   -- Transferring dists/test/main/binary-i386/Packages.gz
   -- Transferring dists/test/main/binary-armhf/Packages
   -- Transferring dists/test/main/binary-armhf/Packages.gz
   -- Transferring dists/test/Release
   -- Transferring dists/test/InRelease
   -- Transferring dists/test/Release.gpg
>> Update complete.
```

Results in:

```
root@5eded8af43c6:/tmp# apt-cache policy graphsurgeon-tf
graphsurgeon-tf:
  Installed: (none)
  Candidate: 8.5.1-1+cuda11.8
  Version table:
     8.5.1-1+cuda11.8 500
        500 https://minio.morph027.de/deb-s3-11 test/main amd64 Packages
root@5eded8af43c6:/tmp# apt-cache show graphsurgeon-tf
Package: graphsurgeon-tf
Version: 8.5.1-1+cuda11.8
License: unknown
Vendor: none
Architecture: amd64
Maintainer: cudatools <cudatools@nvidia.com>
Installed-Size: 81
Section: multiverse/devel
Priority: optional
Homepage: http://nourlgiven.example.com/
Filename: pool/test/g/gr/graphsurgeon-tf_8.5.1-1+cuda11.8_amd64.deb
Size: 14636
SHA1: 247f54db8cb8dfe8091dacf12cbd3cdf8b5a2f71
SHA256: a76fdb5834e7f9977d813bebcca197325a8d1f0fd69e4385a94d23f366c0dbc0
MD5sum: bec2793fda6a9911d7a9f7426c91a9b8
Description: GraphSurgeon for TensorRT package
 GraphSurgeon for TensorRT package.
Description-md5: 2ed78147a56e5008fc61f05c12bb0cf5
Source: tensorrt

root@5eded8af43c6:/tmp# apt-get download graphsurgeon-tf
root@5eded8af43c6:/tmp# dpkg -I graphsurgeon-tf_8.5.1-1+cuda11.8_amd64.deb
 new Debian package, version 2.0.
 size 14636 bytes: control archive=916 bytes.
     280 bytes,    10 lines      control
    1340 bytes,    14 lines      md5sums
 Package: graphsurgeon-tf
 Source: tensorrt
 Version: 8.5.1-1+cuda11.8
 Architecture: amd64
 Maintainer: cudatools <cudatools@nvidia.com>
 Installed-Size: 81
 Section: multiverse/devel
 Priority: optional
 Description: GraphSurgeon for TensorRT package
  GraphSurgeon for TensorRT package.
```

**Comment by erikinkinen** [comment]
https://github.com/deb-s3/deb-s3/blob/2ec9c4172013207e2592a5870a0d0af9fe46b002/lib/deb/s3/package.rb#L258

CGI.unescape converst "+" to " ". This happens when reading Packages. So the error occurs only when rewriting old entries which seems to have caused some confusion.

**Comment by Shalankwa** [comment]
Is there an easy way to fix the Package list after this bug happens?
Currently, all our old packages result in 404 errors because of the incorrect Filename path. 

We're able to manually edit the package files and re-upload them... but this is a tedious task...

**Comment by erikinkinen** [comment]
> Is there an easy way to fix the Package list after this bug happens? Currently, all our old packages result in 404 errors because of the incorrect Filename path.
> 
> We're able to manually edit the package files and re-upload them... but this is a tedious task...

I think you should be able to just fix the "Packages" file, edit the check-sums in "Release" and re-sign it.

My use case was an automated upload from a CI/CD service and I just erased the whole repository and re-ran all pipelines.
